#AppBundle
app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#FOSUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Public Pages
home:
    path: /
    defaults: {_controller: AppBundle:Default:index}

#Secure Pages

admin_dashboard:
    path: /admin
    defaults: {_controller: AppB}
