#AppBundle
app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#FOSUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

##Public Pages
language_switcher:
    path: /language/switch/{locale}
    defaults: {_controller: AppBundle:Default:changeLocale, locale: en}




