#AppBundle
app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#FOSUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Public Pages
home:
    path: /
    defaults: {_controller: AppBundle:Default:index}

language_switcher:
    path: /language/switch/{locale}
    defaults: {_controller: AppBundle:Default:changeLocale, locale: en}

#Secure Pages
admin_dasboard:
    path: /admin/dashboard
    defaults: {_controller: AppBundle:Dashboard:adminDashboard}

teacher_dashboard:
    path: /teacher/dashboard
    defaults: {_controller: AppBundle:Dashboard:teacherDashboard}

student_dashboard:
    path: /student/dashboard
    defaults: {_controller: AppBundle:Dashboard:studentDashboard}

dashboard:
    path: /dashboard
    defaults: {_controller: AppBundle:Dashboard:dashboard}

