#AppBundle
app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

arepa_public_api:
    type:   rest
    prefix: /api/public
    resource: "@AppBundle/Resources/config/api-routing.yml"

arepa_secured_api:
    type:   rest
    prefix: /api/secured
    resource: "@AppBundle/Resources/config/api-secured-routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#FOSUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

##Public Pages
language_switcher:
    path: /language/switch/{locale}
    defaults: {_controller: AppBundle:Default:changeLocale, locale: en}




